--
-- Table structure for table `form_clinical_instructions`
--

CREATE TABLE IF NOT EXISTS `form_cbrs_treatment_plan` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `pid` bigint(20) DEFAULT NULL,  
  `user` varchar(255) DEFAULT NULL,
  `encounter` varchar(255) DEFAULT NULL,
  `review` varchar(255) DEFAULT NULL,  
  `participant_name` varchar(255) DEFAULT NULL,
  `medical_id` varchar(255) DEFAULT NULL,
  `date_birth` date DEFAULT NULL,
  `age` varchar(255) DEFAULT NULL,
  `examiner` varchar(255) DEFAULT NULL,
  `practitioner_id` varchar(100) DEFAULT NULL,
  `dsm_diagnoses` text DEFAULT NULL,
  `last_scan_date` date DEFAULT NULL,
  `last_examination` varchar(100) DEFAULT NULL,
  `providers_medication_mgt` varchar(255) DEFAULT NULL,
  `providers_psychotherapy` text DEFAULT NULL,
  `critical_strengths` text DEFAULT NULL,
  `educational` varchar(255) DEFAULT NULL,
  `financial` varchar(255) DEFAULT NULL,
  `family` varchar(255) DEFAULT NULL,
  `social_support` varchar(255) DEFAULT NULL,
  `housing` varchar(255) DEFAULT NULL,
  `living_skills` varchar(255) DEFAULT NULL,
  `community` varchar(255) DEFAULT NULL,
  `relationships` varchar(255) DEFAULT NULL,
  `areas_to_be_addressed` text DEFAULT NULL,
  `problem_1_description` text DEFAULT NULL,
  `problem_1_client_goal` text DEFAULT NULL,
  `problem_1_objectives` text DEFAULT NULL,
  `problem_1_objectives_tasks` text DEFAULT NULL,
  `problem_1_date_review` varchar(255) DEFAULT NULL,
  `problem_1_progress_code` int(11) DEFAULT 0,
  `problem_1_comments` text DEFAULT NULL,
  `problem_1_date_target` date DEFAULT NULL,
  `problem_1_date_completion` date DEFAULT NULL,
  `problem_2_description` text DEFAULT NULL,
  `problem_2_client_goal` text DEFAULT NULL,
  `problem_2_objectives` text DEFAULT NULL,
  `problem_2_objectives_tasks` text DEFAULT NULL,
  `problem_2_date_review` date DEFAULT NULL,
  `problem_2_progress_code` int(11) DEFAULT 0,
  `problem_2_comments` text DEFAULT NULL,
  `problem_2_date_target` date DEFAULT NULL,
  `problem_2_date_completion` date DEFAULT NULL,
  `problem_3_description` text DEFAULT NULL,
  `problem_3_client_goal` text DEFAULT NULL,
  `problem_3_objectives` text DEFAULT NULL,
  `problem_3_objectives_tasks` text DEFAULT NULL,
  `problem_3_date_review` date DEFAULT NULL,
  `problem_3_progress_code` int(11) DEFAULT 0,
  `problem_3_comments` text DEFAULT NULL,
  `problem_3_date_target` date DEFAULT NULL,
  `problem_3_date_completion` date DEFAULT NULL,
  `individual_included` varchar(255) DEFAULT NULL,  
  `date` timestamp DEFAULT NULL CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,  
  `activity` TINYINT DEFAULT 1 NULL,
  PRIMARY KEY (`id`)
)ENGINE=InnoDB;

