CREATE TABLE IF NOT EXISTS `form_cm_progress_note` (
  id             bigint(20) NOT NULL,
  date           datetime DEFAULT NULL,
  pid            bigint(20) DEFAULT NULL,
  user           varchar(255) DEFAULT NULL,
  billing_code   varchar(255) DEFAULT NULL,
  dateofservice  varchar(255) DEFAULT NULL,
  starttime      varchar(255) DEFAULT NULL,
  endtime        varchar(255) DEFAULT NULL,
  duration       varchar(255) DEFAULT NULL,
  service_local  tinyint(4) DEFAULT NULL,
  service_with   tinyint(4) DEFAULT NULL,
  service_miles  tinyint(4) DEFAULT NULL,
  obj1_completed tinyint(4) DEFAULT NULL,
  obj1_sub       tinyint(4) DEFAULT NULL,
  obj1_mod       tinyint(4) DEFAULT NULL,
  obj1_min       tinyint(4) DEFAULT NULL,
  obj1_regres    tinyint(4) DEFAULT NULL,
  obj2_completed tinyint(4) DEFAULT NULL,
  obj2_sub       tinyint(4) DEFAULT NULL,
  obj2_mod       tinyint(4) DEFAULT NULL,
  obj2_min       tinyint(4) DEFAULT NULL,
  obj2_regres    tinyint(4) DEFAULT NULL,
  obj3_completed tinyint(4) DEFAULT NULL,
  obj3_sub       tinyint(4) DEFAULT NULL,
  obj3_mod       tinyint(4) DEFAULT NULL,
  obj3_min       tinyint(4) DEFAULT NULL,
  obj3_regres    tinyint(4) DEFAULT NULL,
  narrative      varchar(255) DEFAULT NULL,
  plan_details   text DEFAULT NULL,
  plan_date      datetime DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB;
